
name: trust_investment
description: A new Flutter project.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  responsive_framework: ^1.3.0
  http: ^1.2.2
  web_socket_channel: ^3.0.3
  url_launcher: ^6.2.0
  image_picker: ^1.2.0
  fl_chart: ^1.1.1
  intl: ^0.20.2
  marquee: ^2.2.3
  flutter_fortune_wheel: ^1.2.0
  confetti: ^0.8.0
  shared_preferences: ^2.2.0
  audioplayers: ^6.5.1
  pushable_button: ^0.0.4
  shimmer: ^3.0.0

flutter:

  uses-material-design: true

  # Fonts (to support missing characters like Amharic)
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
    
  # Assets
  assets:
    - assets/images/deposit_2.jpg
    - assets/images/vip_1.jpg
    - assets/images/vip_2.jpg
    - assets/images/vip_3.jpg
    - assets/images/vip_4.jpg
    - assets/images/vip_5.jpg
    - assets/images/vip_6.jpg
    - assets/images/vip_7.jpg
    - assets/images/investment_management.jpg
    - assets/images/telegram_banner.jpg
    - assets/images/withdraw_banner.jpg
    - assets/images/invite_friend.jpg
    - assets/images/buy_vip.jpg
    - assets/images/calander_1.jpg
    - assets/images/lucky_wheal.jpg
    - assets/images/order_now.jpg
    - assets/images/task_1.jpg
    - assets/images/gift_box.jpg
